apiVersion: v2
name: devops-platform
description: DevOps platform Helm chart
type: application
version: 2.0.0
appVersion: "2.0.0"
keywords:
  - devops
  - nodejs
  - kubernetes
maintainers:
  - name: devops-team
    email: devops@example.com
